#define MAP_WIDTH 50
#define MAP_HEIGHT 9
#define BASICA "baseAttacker"
#define FASTA "fastAttacker"
#define CHARGERA "chargerAttacker"
#define BASICT "basicTower"
#define FASTT "fastTower"
#define STRONGT "highDamageTower"
#define SLOWET "slowEffectTower"
